# Generated by Django 3.2.4 on 2024-10-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_noteaccess_noterequestaccess_notesecurityconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='noterequestaccess',
            name='type',
            field=models.IntegerField(choices=[(0, 'request'), (1, 'invite')], default=0),
        ),
    ]
