# Generated by Django 3.2.4 on 2024-10-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_notetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='history',
            field=models.JSONField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='editor_data',
            field=models.JSONField(blank=True, max_length=99999, null=True),
        ),
    ]
