# Generated by Django 3.2.4 on 2024-11-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_noteattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteattachment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
