# Generated by Django 3.2.4 on 2024-11-16 20:05

from django.db import migrations, models
import workspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_auto_20241115_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteattachment',
            name='image',
            field=models.FileField(upload_to=workspace.models.note_directory_path),
        ),
    ]
