# Generated by Django 3.2.4 on 2024-12-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaltarget',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'open'), (1, 'in progress'), (2, 'done')], default=0),
        ),
    ]
