version: '3.9'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '8040:9000'
      - '8041:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=myusername
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=some

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local