# Generated by Django 3.2.4 on 2024-12-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_alter_journey_action_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='action_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
