# Generated by Django 3.2.4 on 2024-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'open'), (1, 'pending'), (2, 'done')], default=0),
        ),
    ]
