# Generated by Django 3.2.4 on 2024-11-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='editor_data',
            field=models.JSONField(blank=True, max_length=99999, null=True),
        ),
    ]
