# Generated by Django 3.2.4 on 2024-11-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_alter_noteattachment_image'),
        ('task', '0008_auto_20241116_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workspace.note'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Google Meet'), (2, 'Zoom'), (3, 'Location'), (4, 'Link')], default=0),
        ),
    ]
