name: Build & Deploy

on:
  push:
    branches: [ "front_prod" ]

  pull_request:
    branches: [ "front_prod" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Open Web Client Directory
        working-directory: .
        run: |
          ls -la

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            front/
            dockerfiles/
            .dockerignore
            front-captain-definition
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.FRONT_APP_NAME }}'
          token: '${{ secrets.FRONT_APP_TOKEN }}'